name: TheGardenSage
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72015
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#655d4e'
    - '#867e71'
    - '#221e0e'
    - '#b1a8a0'
    - '#f3f0ef'
  brandStrength: 0.1875
  lightness: 0.09682917036116123
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
